https://github.com/1larity/ESP32_CAM_AI/blob/master/src/CameraServer.h
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/CameraServer.cpp
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/main.cpp
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/OTAHandler.cpp
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/OTAHandler.h
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/StreamServer.cpp
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/StreamServer.h
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/Utils.h
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/Utils.cpp
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/WiFiManager.cpp
https://github.com/1larity/ESP32_CAM_AI/blob/master/src/WiFiManager.h